Question.destroy_all

Question.create(question_number: 'q1-1', body: 'RDC espace public ouvert polyvalent (murs et cloisons retirés) <br /> Étages: espaces educatifs', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q1-1.svg')
Question.create(question_number: 'q1-2', body: 'Bureaux co-working (bureaux partagés)', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q1-2.svg')
Question.create(question_number: 'q1-3', body: 'Commerces', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q1-3.svg')
Question.create(question_number: 'q1-4', body: 'Espace à usage pluriel', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q1-4.svg')
Question.create(question_number: 'q1-5', body: 'Friche artistique-studios', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q1-5.svg')
Question.create(question_number: 'q1-6', body: 'Espace recherche scientifique', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q1-6.svg')
Question.create(question_number: 'q1-7', body: 'Café', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q1-7.svg')
Question.create(question_number: 'q1-8', body: 'Bureaux', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q1-8.svg')
Question.create(question_number: 'q1-9', body: 'Espaces verts et jardins potagers', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q1-9.svg')
Question.create(question_number: 'q1-10', body: 'Bâtiments fermés au public pour réhabilitation', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q1-10.svg')
Question.create(question_number: 'q1-11', body: 'Maison du projet (accueil/ exposition)', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q1-11.svg')
Question.create(question_number: 'q1-comment')

Question.create(question_number: 'q2-1', body: 'Jardinières mobiles', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q2-1.svg')
Question.create(question_number: 'q2-2', body: 'Stands restauration rapide / stand glacier ', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q2-2.svg')
Question.create(question_number: 'q2-3', body: 'Espace camionnettes restauration - Food truck', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q2-3.svg')
Question.create(question_number: 'q2-4', body: 'Aire de jeux pour enfants', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q2-4.svg')
Question.create(question_number: 'q2-5', body: 'Parasols géants', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q2-5.svg')
Question.create(question_number: 'q2-6', body: 'Espace skateboard', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q2-6.svg')
Question.create(question_number: 'q2-7', body: 'Mur végétal anti-bruit', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q2-7.svg')
Question.create(question_number: 'q2-8', body: 'Surfaces peintes toiles géantes pour artistes', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q2-8.svg')
Question.create(question_number: 'q2-9', body: 'Zones vertes créées par percement de l’asphalte et zones pique-nique', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q2-9.svg')
Question.create(question_number: 'q2-10', body: 'Espace marchés éphémères (parvis + tables)', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q2-10.svg')
Question.create(question_number: 'q2-11', body: 'Jardins potagers dans jardinières mobiles', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q2-11.svg')
Question.create(question_number: 'q2-12', body: 'Treillis avec hamacs', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q2-12.svg')
Question.create(question_number: 'q2-13', body: 'Mobilier urbain reconfigurable', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q2-13.svg')
Question.create(question_number: 'q2-14', body: 'Nouvelle station Néobus', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q2-14.svg')
Question.create(question_number: 'q2-comment')

Question.create(question_number: 'q3-1', body: 'Voie Express #1 déplacée', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q3-1.svg')
Question.create(question_number: 'q3-2', body: 'Voie Néobus retracée et réaménagée + Arrêts', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q3-2.svg')
Question.create(question_number: 'q3-3', body: 'Voie Karuia bus + Arrêts', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q3-3.svg')
Question.create(question_number: 'q3-4', body: 'Voie bus Raï + Gare Routière', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q3-4.svg')
Question.create(question_number: 'q3-5', body: 'Voie petit train', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q3-5.svg')
Question.create(question_number: 'q3-6', body: 'Voie cyclable + Vélib’', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q3-6.svg')
Question.create(question_number: 'q3-7', body: 'Voie piétonne', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q3-7.svg')
Question.create(question_number: 'q3-8', body: 'Connections piétonnes', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q3-8.svg')
Question.create(question_number: 'q3-9', body: 'Passerelle végétalisée', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q3-9.svg')
Question.create(question_number: 'q3-10', body: 'Parking en silo avec façades vertes', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q3-10.svg')
Question.create(question_number: 'q3-comment')

Question.create(question_number: 'q4-1', body: 'Parc botanique', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q4-1.svg')
Question.create(question_number: 'q4-2', body: 'Zone village océanien (espace pédagogique, kiosques culinaires, galerie marchande)', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q4-2.svg')
Question.create(question_number: 'q4-3', body: 'Zone culturelle (projection, auditorium, sculptures)', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q4-3.svg')
Question.create(question_number: 'q4-4', body: 'Zone sport urbains (parc parkour et skateboard, espace de danse hip-hop)', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q4-4.svg')
Question.create(question_number: 'q4-5', body: 'Jardins suspendus', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q4-5.svg')
Question.create(question_number: 'q4-6', body: 'Quais flottants avec jardins', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q4-6.svg')
Question.create(question_number: 'q4-7', body: 'Parc linéaire avec promenade', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q4-7.svg')
Question.create(question_number: 'q4-8', body: 'Piscine sur terrasse', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q4-8.svg')
Question.create(question_number: 'q4-9', body: 'Parvis du terminal croisiéristes', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q4-9.svg')
Question.create(question_number: 'q4-10', body: 'Place publique avec jets d’eau', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q4-10.svg')
Question.create(question_number: 'q4-11', body: 'Espaces verts en cœur d’îlot', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q4-11.svg')
Question.create(question_number: 'q4-12', body: 'Littoral aménagé avec places publiques', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q4-12.svg')
Question.create(question_number: 'q4-13', body: 'Amphithéâtre flottant', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q4-13.svg')
Question.create(question_number: 'q4-comment')

Question.create(question_number: 'q5-1', body: 'Cité de la Création et de l\'innovation (hôtel, espaces culturels/musées, commerces...)', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q5-1.svg')
Question.create(question_number: 'q5-2', body: 'Usage mixte: Bureaux + Logements', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q5-2.svg')
Question.create(question_number: 'q5-3', body: 'École de danse avec auditorium', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q5-3.svg')
Question.create(question_number: 'q5-4', body: 'Residentiel avec commerce au rez-de-chaussée', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q5-4.svg')
Question.create(question_number: 'q5-5', body: 'Parking en silo avec façades vertes', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q5-5.svg')
Question.create(question_number: 'q5-6', body: 'Bureaux', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q5-6.svg')
Question.create(question_number: 'q5-7', body: 'Espaces à usage collectif', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q5-7.svg')
Question.create(question_number: 'q5-8', body: 'Terminal croisiéristes', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q5-8.svg')
Question.create(question_number: 'q5-9', body: 'Musée Maritime de Nouvelle-Calédonie avec son pavillon flottant', url: 'https://s3.ca-central-1.amazonaws.com/milieu-noumea/q5-9.svg')
Question.create(question_number: 'q5-comment')
